version: '3.7'
services:
  webserver: 
    image: rconceicaobr/nginx:v1.0
    networks:
      - frontend
    volumes:
      - ./vhosts/default.conf:/etc/nginx/vhosts/default.conf
    ports:
      - 8080:80
networks:
  frontend:
